# Generated by Django 4.2.2 on 2023-06-30 17:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', message='Solo se permiten letras y espacios en los apellidos.')])),
                ('apellidos', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', message='Solo se permiten letras y espacios en los apellidos.')])),
                ('dni', models.IntegerField(unique=True)),
                ('procedimientos', models.IntegerField(choices=[[0, 'Endoscopia'], [1, 'proctoscopia'], [2, 'Colonoscopia'], [3, 'EDA+PROCTO'], [4, 'EDA+COLONO']])),
                ('celular', models.IntegerField()),
                ('doctor', models.IntegerField(choices=[[0, 'Pichilingue'], [1, 'Cesitar'], [2, 'Talia'], [3, 'Carlita'], [4, 'Ivan']])),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
