# Generated by Django 4.2.2 on 2023-06-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimientos',
            old_name='fecha_creacion',
            new_name='fecha_de_cita',
        ),
    ]
